name: Generate Snake Contribution Graph

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake animation 
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake.gif
            background: "#0d1117"          
          color_snake: "#cc00ff"          
          color_dots: "#161b22"           
          color_grid: "#21262d"           

      - name: Push snake animation
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate GitHub contribution snake animation"
          add: "dist/github-snake.svg dist/github-snake.gif"
